//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIConcesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string id_Users { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public int PhoneNumber { get; set; }
        public string id_Cars { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
